global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: 
          - 'book-sharing-backend-1:3000'
          - 'book-sharing-backend-2:3000'
          - 'book-sharing-backend-3:3000'

  - job_name: 'locust'
    static_configs:
      - targets: ['locust-exporter:9300']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
